### ISSUE TITLE
Loader patch question

### ISSUE THREAD

**Issue by pgalonza** [borntohonk/Switch-Ghidra-Guides#17]
Can you help with my question https://gbatemp.net/threads/how-to-create-your-own-sigpatches.616288/post-10448653

> Hi, tell me plz how Loader patches work.As I understand it, package3 is decompressed into several kip files, loader.kip is found > by the hash sum, then we find the offset and replace byte 01 with 00 (cmp w0,w1 to cmp w0,w0). But I still don't understand ?> > what it affects. And why hekate patches offset start after 100 address. And we took hashsum from compressed loader but > patching uncompressed?

I look atmosphere_loader_patch and I'm interested

**Comment by borntohonk** [comment]
All the Patch does is changing a hos version call that compares current version to 10, and if higher run a check, into comparing 0 to 10 and not run the check because it's lower than 10, the specific function you can with ghidra and the .elf of loader when compiling atmosphere, as that has symbols for reading and without compression.

Hekate ignores the header which is 0x100 in size. Only hekate uses this patch as atmosphere doesnt load kip patches anymore, and as I said when I accepted your PR for it, I consider it vanity and a thing I wrote as a joke. 

The code I wrote before your PR was extremely easy to read and understand,  I could revert it if you don't understand your own code.

**Comment by pgalonza** [comment]
Thank you, the code is clear to me, it was interesting exactly how this affects the work of the console, because I have not done this before and use ghidra according to the above instructions. IPS patches were returned when I made changes because part of the community uses a modified fuse and publishes patches with ips support.

**Comment by borntohonk** [comment]
> IPS patches were returned when I made changes because part of the community uses a modified fuse and publishes patches with ips support.

I fundamentally disagree with your choice here, 

there's two kip patches that used to serve a purpose only, and loader patches are for atmospheres open source loader and should never have been .ips patched in the first place.

https://github.com/borntohonk/Atmosphere/blob/master/stratosphere/loader/source/ldr_meta.cpp#L114-L120

this is how to bypass loader.

https://github.com/borntohonk/Atmosphere/blob/master/fusee/program/source/fusee_stratosphere.cpp#L484-L703
https://github.com/borntohonk/Atmosphere/blob/master/fusee/program/source/fusee_stratosphere.cpp#L1057

This is how to deal with FS patches for fusee.

Zero reason to .ips patch loader if you are already forking atmosphere, whoever is distributed a modified fusee just for loading ips patches, does not have my support.

I have reverted your PR to https://github.com/borntohonk/Switch-Ghidra-Guides/blob/master/scripts/atmosphere_loader_patch.py

**Comment by pgalonza** [comment]
I don't understand how I could have caused such a manner of answering with my questions. I just wanted to fill in the gaps in my understanding of the process and systematize the information. I wanted to express my gratitude to you for the answers. But apparently you didn't like something about my questions and actions, which I regret.

**Comment by pgalonza** [comment]
Thank you for your time.
